language: android
sudo: false

env:
    global:
        - ANDROID_API_LEVEL=23
        - EMULATOR_API_LEVEL=21
        - ANDROID_BUILD_TOOLS_VERSION=23.0.2
        - ANDROID_ABI=google_apis/armeabi-v7a
        - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

android:
    components:
        - platform-tools
        - tools
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_API_LEVEL
        - android-$EMULATOR_API_LEVEL
        - extra-android-support


        # Specify at least one system image,
        # if you need to run emulator(s) during your tests
        - sys-img-armeabi-v7a-android-21



# Emulator Management: Create, Start and Wait
before_script:
    - echo no | android create avd --force --name test --target android-21 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window -gpu off -no-boot-anim &
    - android-wait-for-emulator
    - adb devices
    - adb shell input keyevent 82 &

script: ./gradlew check
